package cmd

// Output schemas and runnable examples for every leaf command.
//
// CLI-SPEC §11 forbids stub schemas: each entry names the fields the command
// actually returns and flags the attacker-controllable ones. Caixin echoes
// publisher- and user-supplied text everywhere, so almost every payload has
// untrusted fields; an agent must treat them as data, never as instructions.
//
// A guard test asserts every leaf command resolves to a non-empty schema and at
// least one example, so `reference` cannot silently decay back into stubs.

type outputSchema struct {
	Shape           string   `json:"shape"`
	Fields          []string `json:"fields"`
	UntrustedFields []string `json:"untrusted_fields"`
}

var outputSchemas = map[string]outputSchema{
	"session_status": {
		Shape:  "object",
		Fields: []string{"authenticated", "state_dir", "entitlement_not_implied"},
	},
	"login_challenge": {
		Shape:  "object",
		Fields: []string{"status", "qr_image", "action", "resume", "human_action"},
	},
	"login_result": {
		Shape:  "object",
		Fields: []string{"logged_in", "status", "user"},
		// The nickname is user-supplied text.
		UntrustedFields: []string{"user"},
	},
	"entitlement_report": {
		Shape: "object",
		Fields: []string{"has_active_products", "has_news_subscription", "main_products",
			"additional_entitlements", "single_article_purchases"},
		// Product names are Caixin-supplied marketing text.
		UntrustedFields: []string{"main_products", "additional_entitlements"},
	},
	"logout_result": {
		Shape:  "object",
		Fields: []string{"logged_out"},
	},
	"channel_menu": {
		Shape:           "object",
		Fields:          []string{"data"},
		UntrustedFields: []string{"data"},
	},
	"article_listing": {
		Shape:           "object",
		Fields:          []string{"articles", "page", "page_size", "total", "session_loaded"},
		UntrustedFields: []string{"articles"},
	},
	"newscroll_listing": {
		Shape: "object",
		Fields: []string{"articles", "category", "date", "page", "page_size", "total",
			"returned", "has_more", "listing_only", "session_used"},
		UntrustedFields: []string{"articles"},
	},
	"search_results": {
		Shape: "object",
		Fields: []string{"articles", "category", "page", "page_size", "total", "sort",
			"time_range", "start_time", "end_time", "filter_code"},
		UntrustedFields: []string{"articles"},
	},
	"search_menu": {
		Shape:           "object",
		Fields:          []string{"categories", "time_ranges", "filters"},
		UntrustedFields: []string{"categories"},
	},
	"cxdata_feed": {
		Shape: "object",
		Fields: []string{"items", "category", "name", "page", "page_size", "returned",
			"total", "total_pages", "upstream_page_size", "has_more", "listing_only", "session_used"},
		UntrustedFields: []string{"items"},
	},
	"entity_preview": {
		Shape: "object",
		Fields: []string{"items", "category", "name", "returned", "auth", "is_enterprise",
			"is_cxt_upgrade", "access", "listing_only", "session_used"},
		UntrustedFields: []string{"items"},
	},
	"topic_directory": {
		Shape: "object",
		Fields: []string{"items", "url", "category", "name", "subject", "page", "page_size",
			"start", "total", "returned", "has_more", "directory_only"},
		UntrustedFields: []string{"items"},
	},
	"frontline_listing": {
		Shape:           "object",
		Fields:          []string{"items", "page", "page_size", "has_more"},
		UntrustedFields: []string{"items"},
	},
	"frontline_item": {
		Shape:           "object",
		Fields:          []string{"item"},
		UntrustedFields: []string{"item"},
	},
	"bloggers_directory": {
		Shape: "object",
		Fields: []string{"modules", "modules_count", "items_count", "unique_urls_count",
			"sort", "page", "returned", "duplicates_dropped",
			"unreadable_entries_dropped", "reported_total_pages",
			"reported_total_elements", "reported_first_page", "reported_last_page",
			"pagination", "latest_article_date", "stale_content", "source",
			"source_mode", "session_used", "directory_only",
			"article_details_not_fetched", "javascript_executed",
			"rendered_visibility_verified", "external_stylesheets_applied",
			"complete_listing_verified", "automatic_continuation_followed",
			"search_not_called", "linked_pages_not_fetched", "scripts_not_executed"},
		// Blogger names and self-descriptions are user-supplied.
		UntrustedFields: []string{"modules"},
	},
	"article_body": {
		Shape: "object",
		Fields: []string{"url", "title", "author", "editor", "source", "published_at",
			"paragraphs", "paragraph_count", "content_chars", "images",
			"paywall_present", "entitled", "complete", "body_delivered_by_script", "session_used",
			"source_mode", "entitlement_marker",
			"javascript_executed", "content_advisory"},
		// Body text is publisher-supplied. A live article was observed carrying
		// an imperative sentence addressed at summarizing AIs.
		UntrustedFields: []string{"title", "author", "paragraphs", "images"},
	},
	"route_verdict": {
		Shape: "object",
		Fields: []string{"input_url", "canonical_url", "supported", "command", "adapter",
			"discovery_required", "content_access_not_implied", "reason"},
		UntrustedFields: []string{"input_url"},
	},
	"reference_document": {
		Shape: "object",
		Fields: []string{"tool", "version", "schema_version", "risk_tier", "minimum_skill_version",
			"release_readiness", "commands", "schemas", "exit_codes", "global_options", "security", "output"},
	},
	"context_document": {
		Shape: "object",
		Fields: []string{"tool", "version", "schema_version", "env", "account", "config",
			"credentials", "update", "skill"},
	},
	"doctor_report": {
		Shape:  "object",
		Fields: []string{"checks"},
	},
	"channel_snapshot": {
		Shape: "object",
		Fields: []string{"page_kind", "title", "modules", "modules_count", "items_count",
			"navigation", "navigation_count", "source", "source_mode", "session_used",
			"javascript_executed", "rendered_visibility_verified",
			"external_stylesheets_applied", "complete_listing_verified"},
		// Everything on a front page is publisher-supplied text.
		UntrustedFields: []string{"title", "modules", "navigation"},
	},
	"update_result": {
		Shape: "object",
		Fields: []string{"status", "stage", "previous_version", "current_version",
			"target_version", "update_available", "install_method", "binary_replaced",
			"signature_status", "signature_verified", "checksum_status",
			"skill_sync_status", "skill_sync_command", "release_url", "notice"},
	},
	"public_directory": {
		Shape: "object",
		Fields: []string{"kind", "title", "modules", "modules_count", "items_count",
			"unique_urls_count", "page", "pagination", "subdirectories", "downloads",
			"downloads_count", "latest_article_date", "stale_content", "source",
			"source_mode", "session_used", "directory_only",
			"article_details_not_fetched", "interactive_projects_not_fetched",
			"javascript_executed", "scripts_not_executed",
			"rendered_visibility_verified", "rendered_visibility_not_verified",
			"external_stylesheets_applied", "complete_listing_verified"},
		UntrustedFields: []string{"title", "modules", "subdirectories", "downloads"},
	},
	"esg30_subdirectory": {
		Shape: "object",
		Fields: []string{"kind", "title", "section_profile", "modules", "modules_count",
			"items_count", "unique_urls_count", "pagination", "latest_article_date",
			"stale_content", "source", "source_mode", "session_used", "directory_only",
			"article_details_not_fetched", "javascript_executed", "scripts_not_executed",
			"rendered_visibility_verified", "rendered_visibility_not_verified",
			"external_stylesheets_applied", "external_stylesheets_not_fetched",
			"complete_listing_verified", "linked_pages_not_fetched"},
		UntrustedFields: []string{"title", "modules", "section_profile"},
	},
	"section_directory": {
		Shape: "object",
		Fields: []string{"kind", "title", "directory_title", "modules", "modules_count",
			"items_count", "unique_urls_count", "page", "latest_article_date",
			"stale_content", "continuation_available", "continuation_not_followed",
			"source", "source_mode", "session_used", "directory_only",
			"article_details_not_fetched", "javascript_executed", "scripts_not_executed",
			"rendered_visibility_verified", "external_stylesheets_applied",
			"complete_listing_verified", "linked_pages_not_fetched"},
		UntrustedFields: []string{"title", "directory_title", "modules"},
	},
	"issue_contents": {
		Shape: "object",
		Fields: []string{"url", "publication", "issue_number", "title", "issue_title",
			"source_label", "total_issue", "annual_issue", "published_at", "magazine_id",
			"cover_image", "sections", "articles_count", "directory_only"},
		UntrustedFields: []string{"title", "issue_title", "source_label", "sections"},
	},
	"blog_author": {
		Shape: "object",
		Fields: []string{"author_key", "title", "profile", "modules", "modules_count",
			"items_count", "unique_urls_count", "pagination", "load_more_available",
			"reported_author_id", "reported_articles_count",
			"reported_last_published_at", "reported_last_published_at_ms",
			"latest_article_date", "stale_content", "source", "source_mode",
			"session_used", "directory_only", "article_details_not_fetched",
			"javascript_executed", "rendered_visibility_verified",
			"external_stylesheets_applied", "complete_listing_verified"},
		UntrustedFields: []string{"title", "profile", "modules"},
	},
	"culture_section": {
		Shape: "object",
		Fields: []string{"section_key", "name", "title", "modules", "modules_count",
			"items_count", "unique_urls_count", "page", "pagination",
			"latest_article_date", "sidebar_latest_article_date", "stale_content",
			"source", "session_used", "directory_only",
			"article_details_not_fetched", "javascript_executed", "scripts_not_executed",
			"rendered_visibility_verified", "external_stylesheets_applied",
			"complete_listing_verified", "linked_pages_not_fetched",
			"transactions_not_started"},
		UntrustedFields: []string{"title", "name", "modules"},
	},
	"culture_author": {
		Shape: "object",
		Fields: []string{"author_key", "title", "profile", "modules", "modules_count",
			"items_count", "unique_urls_count", "article_items_count",
			"author_links_count", "pagination", "latest_article_date", "stale_content",
			"source", "session_used", "directory_only", "article_details_not_fetched",
			"javascript_executed", "scripts_not_executed", "load_more_not_called",
			"rendered_visibility_verified", "external_stylesheets_applied",
			"complete_listing_verified", "linked_pages_not_fetched"},
		UntrustedFields: []string{"title", "profile", "modules"},
	},
	"topic_listing": {
		Shape: "object",
		Fields: []string{"topic_listing_only", "topic_surface", "url", "topic_type",
			"data_code", "title", "description", "image", "updated_at", "sections",
			"sections_count", "items_count", "tabs_count", "paywall_components",
			"details_not_fetched", "unsupported_components", "pagination_not_guessed"},
		// Every section title, headline, and summary is publisher-supplied.
		UntrustedFields: []string{"title", "description", "sections"},
	},
	"microsite_surface": {
		Shape: "object",
		Fields: []string{"kind", "sponsored", "title", "title_source", "modules",
			"modules_count", "items_count", "unique_urls_count", "subdirectories",
			"downloads", "downloads_count", "external_links_count",
			"media_elements_count", "scripts_count", "forms_count", "iframes_count",
			"pagination", "latest_article_date", "stale_content", "source",
			"session_used", "directory_only", "article_details_not_fetched",
			"description_not_extracted", "arbitrary_text_not_extracted",
			"rendered_visibility_not_verified", "rendered_visibility_verified",
			"external_stylesheets_not_fetched", "external_stylesheets_applied",
			"page_navigation_not_extracted", "javascript_executed",
			"complete_listing_verified", "scripts_not_executed", "forms_not_submitted",
			"iframes_ignored", "media_not_downloaded", "downloads_not_fetched",
			"external_links_not_fetched", "linked_pages_not_fetched",
			"section_profile", "esg30_branded_resource", "promote_directory_resource",
			"resource_body_not_extracted", "source_mode"},
		// Campaign copy and link labels are written by the sponsor.
		UntrustedFields: []string{"title", "modules", "subdirectories", "downloads",
			"section_profile"},
	},
	"interactive_project": {
		Shape: "object",
		Fields: []string{"kind", "directory_title", "title", "heading_candidate",
			"description", "public_intro", "modules", "modules_count", "items_count",
			"unique_urls_count", "paywall_present", "paywall_content_not_extracted",
			"scripts_count", "forms_count", "iframes_count", "canvas_count", "svg_count",
			"latest_article_date", "stale_content", "source", "source_mode",
			"session_used", "directory_only", "article_details_not_fetched",
			"javascript_executed", "rendered_visibility_verified",
			"external_stylesheets_applied", "complete_listing_verified",
			"interactive_content_not_rendered", "external_dependencies_not_fetched",
			"scripts_not_executed", "iframes_not_loaded", "forms_not_submitted",
			"linked_pages_not_fetched", "shared_navigation_not_included"},
		UntrustedFields: []string{"title", "directory_title", "heading_candidate",
			"description", "public_intro", "modules"},
	},
	"opinion_directory": {
		Shape: "object",
		Fields: []string{"kind", "directory_title", "title", "page", "modules",
			"modules_count", "items_count", "unique_urls_count", "returned",
			"reported_total", "reported_maxes", "upstream_version", "pagination",
			"latest_article_date", "stale_content", "source", "source_mode",
			"session_used", "directory_only", "article_details_not_fetched",
			"javascript_executed", "rendered_visibility_verified",
			"external_stylesheets_applied", "complete_listing_verified",
			"scripts_not_executed", "linked_pages_not_fetched"},
		UntrustedFields: []string{"title", "directory_title", "modules"},
	},
	"opinion_author": {
		Shape: "object",
		Fields: []string{"author_key", "title", "profile", "directory_profile",
			"modules", "modules_count", "items_count", "unique_urls_count", "page",
			"returned", "reported_author_id", "reported_subject_id", "reported_maxes",
			"upstream_version", "pagination", "load_more_available",
			"latest_article_date", "stale_content", "source", "session_used",
			"directory_only", "article_details_not_fetched", "javascript_executed",
			"rendered_visibility_verified", "external_stylesheets_applied",
			"complete_listing_verified", "load_more_not_called",
			"author_search_not_called", "scripts_not_executed",
			"linked_pages_not_fetched"},
		// The bio and every headline are publisher- or author-supplied.
		UntrustedFields: []string{"title", "profile", "directory_profile", "modules"},
	},
	"video_section": {
		Shape: "object",
		Fields: []string{"page_kind", "title", "page", "modules", "modules_count",
			"items_count", "unique_urls_count", "returned", "reported_maxes",
			"upstream_version", "template_classes", "empty_visible_directory",
			"pagination", "latest_article_date", "stale_content", "source",
			"source_mode", "session_used", "directory_only",
			"article_details_not_fetched", "javascript_executed",
			"rendered_visibility_verified", "external_stylesheets_applied",
			"complete_listing_verified", "media_streams_not_fetched",
			"media_not_downloaded"},
		UntrustedFields: []string{"title", "modules"},
	},
	"changelog_document": {
		Shape:  "object",
		Fields: []string{"current_version", "since", "entries"},
	},
}

var commandSchemas = map[string]string{
	"status":                   "session_status",
	"entitlements":             "entitlement_report",
	"login":                    "login_challenge",
	"login-resume":             "login_result",
	"logout":                   "logout_result",
	"channels":                 "channel_menu",
	"latest":                   "article_listing",
	"newscroll":                "newscroll_listing",
	"search":                   "search_results",
	"search-menu":              "search_menu",
	"cxdata-feed":              "cxdata_feed",
	"entities-preview":         "entity_preview",
	"topics":                   "topic_directory",
	"frontline":                "frontline_listing",
	"frontline-detail":         "frontline_item",
	"bloggers-directory":       "bloggers_directory",
	"article":                  "article_body",
	"snapshot":                 "channel_snapshot",
	"public-directory":         "public_directory",
	"esg30-subdirectory":       "esg30_subdirectory",
	"section-directory":        "section_directory",
	"issue":                    "issue_contents",
	"blog-author":              "blog_author",
	"culture-section":          "culture_section",
	"culture-author":           "culture_author",
	"topic":                    "topic_listing",
	"microsite":                "microsite_surface",
	"esg30-resource":           "microsite_surface",
	"datanews-interactive":     "interactive_project",
	"opinion-columns":          "opinion_directory",
	"opinion-upfront":          "opinion_directory",
	"opinion-author-directory": "opinion_directory",
	"opinion-author":           "opinion_author",
	"video-section":            "video_section",
	"route":                    "route_verdict",
	"reference":                "reference_document",
	"context":                  "context_document",
	"doctor":                   "doctor_report",
	"changelog":                "changelog_document",
	"update":                   "update_result",
}

// untrustedFieldsFor resolves the untrusted field list a command's declared
// schema promises, so the runtime marker and `reference` are the same statement.
func untrustedFieldsFor(command string) []string {
	return outputSchemas[commandSchemas[command]].UntrustedFields
}

var commandExamples = map[string][]string{
	"status":                   {"caixin-cli status --compact"},
	"login":                    {"caixin-cli login --compact"},
	"login-resume":             {"caixin-cli login-resume --compact"},
	"entitlements":             {"caixin-cli entitlements --compact"},
	"logout":                   {"caixin-cli logout"},
	"channels":                 {"caixin-cli channels --compact"},
	"latest":                   {"caixin-cli latest --size 20 --compact"},
	"newscroll":                {"caixin-cli newscroll --compact", "caixin-cli newscroll --date 2026-08-06 --compact"},
	"search":                   {"caixin-cli search \"经济\" --size 10 --compact"},
	"search-menu":              {"caixin-cli search-menu --compact"},
	"cxdata-feed":              {"caixin-cli cxdata-feed latest --size 25 --compact"},
	"entities-preview":         {"caixin-cli entities-preview companies --compact"},
	"topics":                   {"caixin-cli topics https://topics.caixin.com/economy/ --page 1 --size 25 --compact"},
	"frontline":                {"caixin-cli frontline --size 20 --compact"},
	"frontline-detail":         {"caixin-cli frontline-detail <32-hex-code> --compact"},
	"bloggers-directory":       {"caixin-cli bloggers-directory --page 1 --sort latest --compact"},
	"article":                  {"caixin-cli article \"https://www.caixin.com/2026-08-07/102472114.html\" --compact", "caixin-cli article \"https://www.caixin.com/2026-08-07/102472114.html\" --full --compact"},
	"culture-author":           {"caixin-cli culture-author https://culture.caixin.com/daoerdeng/ --compact"},
	"culture-section":          {"caixin-cli culture-section https://culture.caixin.com/zhuanlan/ --compact"},
	"blog-author":              {"caixin-cli blog-author https://iscientists.blog.caixin.com --compact"},
	"issue":                    {"caixin-cli issue https://weekly.caixin.com/2026/cw1217/ --compact"},
	"section-directory":        {"caixin-cli section-directory https://finance.caixin.com/regulation/ --compact"},
	"esg30-subdirectory":       {"caixin-cli esg30-subdirectory https://index.caixin.com/news/ --compact"},
	"public-directory":         {"caixin-cli public-directory https://datanews.caixin.com/datatopic/ --compact"},
	"snapshot":                 {"caixin-cli snapshot https://datanews.caixin.com/ --compact"},
	"topic":                    {"caixin-cli topic https://key.caixin.com/topic/BQ02.000000368 --compact", "caixin-cli topic https://deepview.caixin.com/topic/BQ02.000008008.html --compact"},
	"microsite":                {"caixin-cli microsite https://topics.caixin.com/2025/caixin_summit2025/ --compact"},
	"esg30-resource":           {"caixin-cli esg30-resource https://promote.caixin.com/gzlfz/ --compact"},
	"datanews-interactive":     {"caixin-cli datanews-interactive https://datanews.caixin.com/interactive/2019/covers/ --compact"},
	"opinion-columns":          {"caixin-cli opinion-columns https://opinion.caixin.com/columns/ --compact", "caixin-cli opinion-columns https://opinion.caixin.com/columns/ --page 2 --compact"},
	"opinion-upfront":          {"caixin-cli opinion-upfront https://opinion.caixin.com/upfront/ --compact"},
	"opinion-author-directory": {"caixin-cli opinion-author-directory https://opinion.caixin.com/columns-test/ --page 1 --compact"},
	"opinion-author":           {"caixin-cli opinion-author https://opinion.caixin.com/wuqianli_mjxx/ --compact", "caixin-cli opinion-author https://opinion.caixin.com/wuqianli_mjxx/ --discovery-source author-directory --directory-page 1 --compact"},
	"video-section":            {"caixin-cli video-section https://video.caixin.com/dr/ --compact"},
	"route":                    {"caixin-cli route \"https://www.caixin.com/2026-08-06/102472081.html\" --compact"},
	"reference":                {"caixin-cli reference --compact"},
	"context":                  {"caixin-cli context --compact"},
	"doctor":                   {"caixin-cli doctor --compact"},
	"update":                   {"caixin-cli update --check --compact", "caixin-cli update --compact"},
	"changelog":                {"caixin-cli changelog --since 0.1.0 --compact"},
}
